### ISSUE TITLE
Backpack selection in char setup broken

### ISSUE THREAD

**Issue by comma** [Yonaguni/Baystation12#38]
#### Description of issue
Options get you wrong backpack type.
"Satchel" -> backpack
"Satchel Alt" -> satchel
"Backpack" -> satchel alt

#### Difference between expected and actual behavior
Expected: get what's on label
Actual: wrong value

#### Steps to reproduce 
Go to char setup.
Select backpack.
Cry as you never asked for satchel.

#### Specific information for locating

"Satchel Alt" somewhere in modules/client I dunno

#### Length of time in which bug has been known to occur

At least since ten minutes ago

#### Server revision & Game ID

effort

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Zuhayr** [comment]
SATCHEL SUPERIOR.
