### ISSUE TITLE
Power alarms emit broken hrefs

### ISSUE THREAD

**Issue by thasc** [Yonaguni/Baystation12#71]
#### Description of issue

--- Power Alarms Detected ---
Engine Room! (<A HREF=?src=[0x300001d];switchcamera=[icon-camera (NORTH)]>|<A HREF=?src=[0x300001d];switchcamera=[icon-camera (NORTH)]>|<A HREF=?src=[0x300001d];switchcamera=[icon-camera (EAST)]>|<A HREF=?src=[0x300001d];switchcamera=[icon-camera (WEST)]>|<A HREF=?src=[0x300001d];switchcamera=[icon-camera (EAST)]>|<A HREF=?src=[0x300001d];switchcamera=[icon-camera (WEST)]>)

#### Steps to reproduce 

Should occur with any power alarm, I suppose.

#### Length of time in which bug has been known to occur

Unknown.

#### Server revision & Game ID

Revision unknown
Game ID: bLw-alBE
BYOND version: 510

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Zuhayr** [comment]
Looks like this was due to cameras with no c_tag set.
