### ISSUE TITLE
Transmute cannot be used

### ISSUE THREAD

**Issue by Datraen** [Yonaguni/Baystation12#74]
#### Description of issue
Transmute provided error messages, 

You cannot use this power at close range.
You cannot use this power at a distance.

indicating that it cannot be used.

#### Difference between expected and actual behavior
Expected to be able to use Transmute at close range or at a distance.

#### Steps to reproduce 
Manifest Transmute
Cry as your powers are useless

#### Specific information for locating
Transmute, iron coin

#### Length of time in which bug has been known to occur
Unknown

#### Server revision & Game ID
Game ID: bLw-aHyH

#### Issue bingo
- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Zuhayr** [comment]
Unimplemented, not a bug.

**Comment by Zuhayr** [comment]
#75
