### ISSUE TITLE
Turtleneck is not working from loadout

### ISSUE THREAD

**Issue by anagilehippo** [Yonaguni/Baystation12#85]
#### Description of issue
Clothing loadout for turtleneck does not work.

#### Difference between expected and actual behavior
When equipped it does not show up on your sprite but appears on your character description when your sprite is identified

#### Steps to reproduce 
Equip turtleneck

#### Specific information for locating

That's a turtleneck shirt. It is a small item.
A thick, black turtleneck shirt. For when the air gets a bit chilly.

#### Server revision & Game ID

Says revision unknown. Rip. 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Zuhayr** [comment]
This is a general issue with shirts, I don't think accessories are applied properly when the mannequin is dressed.
